### PR TITLE
feat-alert

### PR DESCRIPTION
**Pull request by iamsaurav28**
Screenshot (58)

### CODE REVIEW

**Review by therajatg — APPROVED** [review]
Looks good to me.

**Review by kjais1720 — CHANGES_REQUESTED** [review]
Use  proper & descriptive names for your classes, the classes like `.al, .i` are not really understandable, here you can replace the `.al` with `.alert`, similarly for other classes, give them such a name that describes what it does

**Comment by iamsaurav28** [comment]
> Use proper & descriptive names for your classes, the classes like `.al, .i` are not really understandable, here you can replace the `.al` with `.alert`, similarly for other classes, give them such a name that describes what it does

done as u suggested.

**Review by kjais1720 — APPROVED** [review]
All good now👍

**Pull request merged**
